name: Test

on:
  push:

jobs:

  compile:
    runs-on: ubuntu-latest
    name: Running Java 17 compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile code
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run unit tests
        run: mvn test -B verify

  build:
    runs-on: ubuntu-latest
    name: mvn build
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build
        run: mvn clean package -DskipTests